spring.application.name=TaskManager
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
org.gradle.configuration-cache=true

# Max file size for a single request
spring.servlet.multipart.max-file-size=10MB

# Max total request size for a multi-file upload
spring.servlet.multipart.max-request-size=10MB